jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        memory:
            max: 1024
            def: 1024
        ui:
            def: 'terminal'


profile::accounts::skel_archives:
    - filename: shell-lesson-data.zip
      source: https://swcarpentry.github.io/shell-novice/data/shell-lesson-data.zip
