jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 4098
            def: 4098
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::kernel::venv::packages: ['pennylane==0.37.0', 'numpy', 'pandas', 'matplotlib']

profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'python/3.11']

profile::accounts::skel_archives:
    - filename: ciq101-2-a24-FR-main.zip
      source: https://github.com/calculquebec/ciq101-2-a24-FR/archive/refs/heads/main.zip
    - filename: cache.zip
      source: https://drive.google.com/uc?id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH&export=download
    - filename: jupyter.zip
      source: https://drive.google.com/uc?id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB&export=download
