jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib']  # Pour démos en bonus

profile::accounts::skel_archives:
    - filename: PYT101-2025-main.zip
      source: https://github.com/calculquebec/PYT101-2025/archive/refs/heads/main.zip
