jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib']

profile::accounts::skel_archives:
    - filename: intro-programmation-python-main.zip
      source: https://github.com/calculquebec/intro-programmation-python/archive/refs/heads/main.zip
