jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 2048
            def: 2048
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.10
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
    PIP_CONFIG_FILE: /cvmfs/soft.computecanada.ca/config/python/pip-avx2-gentoo.conf
jupyterhub::kernel::venv::packages: ['numpy<2', 'pandas', 'matplotlib']
profile::software_stack::lmod_default_modules: ['StdEnv/2020']

profile::accounts::skel_archives:
    - filename: python-novice-inflammation-data.zip
      source: https://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip

    - filename: jupyter.zip
      source: https://drive.google.com/uc?export=download&id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB

    - filename: matplotlib.zip
      source: https://drive.google.com/uc?export=download&id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH
