profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'gcc', 'cuda/12.2', 'mpi4py/4.0.3', 'opencv/4.13.0', 'jupyterlab-apps/1.0', 'python/3.13', 'ipython-kernel/3.13']
jupyterhub::kernel::venv::packages:
  - numpy>2
  - pandas==3.0.0
  - matplotlib==3.10.8
  - dask[array,distributed,diagnostics]==2026.1.2
  - graphviz
  - sparse
  - scipy==1.17.0
  - numba==0.65.0
  - torch==2.10.0
  - scikit-learn
  - pillow
  - pycuda==2025.1
  - torchvision
  - torch
  - transformers
  - vllm==0.21.0

jupyterhub::kernel::venv::pip_environment:
  PIP_NO_INDEX: 1
  PYTHONPATH: /cvmfs/soft.computecanada.ca/easybuild/python/site-packages:/cvmfs/soft.computecanada.ca/custom/python/site-packages
  EBPYTHONPREFIXES: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/scipy-stack/2026a:/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcc12/opencv/4.13.0:/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcc12/opencv/4.13.0:/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/MPI/gcc12/openmpi4/mpi4py/4.0.3:/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/ipykernel/2026a
  
