jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 2
            max: 2
        memory:
            min: 1024
            max: 3000
            def: 3000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
jupyterhub::kernel::venv::packages: ['pyspark', 'numpy', 'pandas<2.0.0']


# Load the same python as the kernel to trigger site-packages visibility
profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'gcc', 'python/3.9', 'spark', 'arrow']

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/cq_formation_spark/archive/refs/heads/main.zip
    - filename: cache.zip
      source: https://drive.google.com/uc?id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH&export=download
    - filename: jupyter.zip
      source: https://drive.google.com/uc?id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB&export=download
