jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib']  # Pour démos en bonus

profile::accounts::skel_archives:
    - filename: pytshs101-main.zip
      source: https://github.com/calculquebec/pyt-shs101/archive/refs/heads/main.zip
