jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        nprocs:
            def: 4
            max: 4
        memory:
            max: 22000
            def: 21000
        gpus:
            def: 'gpu:1'
            choices: ['gpu:1']

jupyterhub::kernel::venv::packages: ['cupy', 'jax==0.4.30', 'torchvision', 'matplotlib']

profile::freeipa::mokey::enable_user_signup: true
profile::freeipa::mokey::require_verify_admin: false

profile::accounts::skel_archives:
    - filename: master.zip
      source: https://github.com/calculquebec/formation_cpu-gpu/archive/refs/heads/master.zip
    - filename: cifar-10-python.tar.gz
      source: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
