jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 4098
            def: 4098
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::enable_otp_auth: false

jupyterhub::admin_groups: ['helper']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']

jupyterhub::kernel::venv::packages: ['cirq==1.1.0']

profile::users::ldap::users:
    user:
        count: 50
        passwd: # SET THE PASSWD
        groups: ['def-sponsor00']

    instructor:
        passwd: # SET THE PASSWD
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: # SET THE PASSWD
        groups: ['def-sponsor00', 'helper']
