jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 2
            max: 2
        memory:
            min: 1024
            max: 3000
            def: 3000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true
        start_timeout: 900
        http_timeout: 300

jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.11
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
    PIP_CONFIG_FILE: /cvmfs/soft.computecanada.ca/config/python/pip-avx2-gentoo.conf
jupyterhub::kernel::venv::packages: ['numpy', 'matplotlib']
profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'python/3.11.5', 'ir-kernel/4.4', 'ijulia-kernel/1.10']

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/lab101-exercices/archive/refs/heads/main.zip

    - filename: jupyter.zip
      source: https://drive.google.com/uc?export=download&id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB

    - filename: matplotlib.zip
      source: https://drive.google.com/uc?export=download&id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH
