jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    account:
      def: 'def-sponsor00'
    runtime:
      min: 3.5
      def: 4.0
      max: 5.0
    nprocs:
      min: 1
      def: 2
      max: 2
    memory:
      min: 1024
      max: 3000
      def: 3000
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: true
    start_timeout: 900
    http_timeout: 300

jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.11.5/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.11
jupyterhub::kernel::venv::pip_environment:
  PIP_NO_INDEX: 1
  PIP_CONFIG_FILE: /cvmfs/soft.computecanada.ca/config/python/pip-avx2-gentoo.conf
jupyterhub::kernel::venv::packages: ['numpy', 'matplotlib']
profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'python/3.11.5', 'ir-kernel/4.2', 'ijulia-kernel/1.8']

profile::accounts::skel_archives:
  - filename: main.zip
    source: https://github.com/calculquebec/lab101-exercices/archive/refs/heads/main.zip

  - filename: jupyter.zip
    source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1/jupyter-v1.zip

  - filename: cache.zip
    source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip

formation_extra::google_calendar_id: "%{alias('google_calendar_id')}"
formation_extra::google_api_key: "%{alias('google_api_id')}"
formation_extra::course: "%{alias('cluster_name')}"

cron::job:
  spawn_nodes:
    command: "/usr/sbin/is_event_soon.py --delay 30 --config /etc/cq_event_check.ini || /opt/software/slurm/bin/scontrol update node=ALL state=power_up"
    minute: '*/15'
    hour: '*'
    date: '*'
    month: '*'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes'
    environment: ['CRON_TZ=America/New_York']
