jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 4
            max: 4
        memory:
            min: 1024
            max: 14000
            def: 14000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'terminal'
    SlurmFormSpawner:
        disable_form: true

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'gcc/9']

profile::accounts::skel_archives:
    - filename: main-nbody.zip
      source: https://github.com/calculquebec/cq-formation-nbody/archive/refs/heads/main.zip
    - filename: main-convolution.zip
      source: https://github.com/calculquebec/cq-formation-convolution/archive/refs/heads/main.zip
