jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 4
            max: 4
        memory:
            min: 1024
            max: 22000
            def: 21000
        gpus:
            def: 'gpu:1'
            choices: ['gpu:1']
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab' # ['notebook', 'lab', 'terminal']
    SlurmFormSpawner:
        disable_form: true

jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.10
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
    PIP_CONFIG_FILE: /cvmfs/soft.computecanada.ca/config/python/pip-avx2-gentoo.conf
jupyterhub::kernel::venv::packages: ['numba==0.53.1', "numpy==1.23.5", 'pycuda', 'matplotlib']

profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'gcc', 'cuda']

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/cq-intro-python-gpu/archive/refs/heads/main.zip
    - filename: cache.zip
      source: https://drive.google.com/uc?id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH&export=download
    - filename: jupyter.zip
      source: https://drive.google.com/uc?id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB&export=download
