jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 1024
            def: 1024
        oversubscribe:
            def: true
            lock: true
        partition:
            def: 'node'
            lock: true
        ui:
            def: 'terminal'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::enable_otp_auth: false

jupyterhub::admin_groups: ['helper']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']

jupyterhub::kernel::venv::packages: ['numpy', 'cupy']

# Private terraform token, and specific terraform cloud workspace
profile::slurm::base::slurm_version: '23.02'
profile::slurm::controller::tfe_token: rXZ2Dz6TVUv95Q.atlasv1.BVkPjLcw6nf1K8o0dXU8v9ujj6p1bhzr4zSAJ0qdRLANO62RTZ6FDBV7UF2NoRgUuNk
profile::slurm::controller::tfe_workspace: ws-SuRUmESWUVWicpiK

profile::users::ldap::users:
    user:
        count: 50
        passwd: # SET THE PASSWD
        groups: ['def-sponsor00']

    instructor:
        passwd: # SET THE PASSWD
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: # SET THE PASSWD
        groups: ['def-sponsor00', 'helper']

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/cip201-serveurs-calcul/archive/refs/heads/main.zip
    - filename: will-cite.zip
      source: https://drive.google.com/uc?export=download&id=11vO_wCCvUUGxg6JmpvQjck6Q6WU-LL9t
