jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 1024
            def: 1024
        oversubscribe:
            def: true
            lock: true
        partition:
            def: 'node'
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

profile::freeipa::mokey::enable_user_signup: false
profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']

lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
jupyterhub::kernel::venv::packages: ['numpy', 'cupy']

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/cip201-serveurs-calcul/archive/refs/heads/main.zip
    - filename: will-cite.zip
      source: https://drive.google.com/uc?export=download&id=11vO_wCCvUUGxg6JmpvQjck6Q6WU-LL9t
