jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 1024
            def: 1024
        oversubscribe:
            def: true
            lock: true
        partition:
            def: 'node'
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'gcc/9', 'openmpi/4.0.3', 'boost-mpi/1.72.0']

profile::accounts::skel_archives:
    - filename: main-mpi201-prog-parallele
      source: https://github.com/calculquebec/mpi201-prog-parallele/archive/refs/heads/main.zip
    - filename: main-nbody.zip
      source: https://github.com/calculquebec/cq-formation-nbody/archive/refs/heads/main.zip
    - filename: main-convolution.zip
      source: https://github.com/calculquebec/cq-formation-convolution/archive/refs/heads/main.zip
