#!/bin/bash

# Copy this template to $(git rev-parse --show-toplevel)/.git/hook/pre-commit
# Ensure it is executable : chmod +x .git/hook/pre-commit

# Before commit, check staged files for yaml issues.

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -e "\.yaml$" -e "\.yml$")

for file in $STAGED_FILES
do
	exec yamllint --no-warning $file
done
