jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 3000
            def: 3000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true


jupyterhub::admin_groups: ['helper']

lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib', 'plotnine']
jupyterhub::kernel::venv::python: "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.11.5/bin/python"

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']


# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/analyse-donnees-python/archive/refs/heads/main.zip
