jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 3000
            def: 3000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']
jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib', 'plotnine', 'altair']
jupyterhub::kernel::venv::python: "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.11.5/bin/python"


profile::accounts::skel_archives:
    - filename: analyse-donnees-python-main.zip
      source: https://github.com/calculquebec/analyse-donnees-python/archive/refs/heads/main.zip
    - filename: data-analysis-python-main.zip
      source: https://github.com/calculquebec/data-analysis-python/archive/refs/heads/main.zip
    - filename: cache.zip
      source: https://drive.google.com/uc?id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH&export=download
    - filename: jupyter.zip
      source: https://drive.google.com/uc?id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB&export=download
    - filename: next.zip
      source: https://github.com/vega/vega-datasets/archive/refs/heads/next.zip
