jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        memory:
            max: 4098
            def: 4098

jupyterhub::kernel::venv::packages:
  - aiohttp
  - fsspec
  - h5py
  - numpy
  - pandas
  - matplotlib
  - pennylane
  - pennylane-calculquebec
  - qiskit
  - qiskit-calculquebec
  - mitiq
  - mthree
  - psutil
  - ply
  - platexenc
  

profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'python/3.11', 'jupyterlab-apps/1.0']

profile::accounts::skel_archives:
    - filename: ciq102-main.zip
      source: https://github.com/calculquebec/ciq102/archive/refs/heads/main.zip
    - filename: mnq101-main.zip
      source: https://github.com/calculquebec/mnq101/archive/refs/heads/main.zip

