jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        memory:
            max: 3072
            def: 3072
        ui:
            def: 'lab'

jupyterhub::kernel::venv::packages: ['scikit-learn', 'matplotlib', 'pandas', 'pillow', 'numpy']

profile::accounts::skel_archives:
    - filename: ia101-main.zip  # Utilise le même matériel pour IA101 et IA102
      source: https://github.com/calculquebec/ia102/archive/refs/heads/master.zip
