jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.13.2/bin/python
jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      max: 8.0
      lock: true
    nprocs:
      max: 8
      lock: true
    memory:
      max: 8092
      def: 4048
      lock: true
    gpus:
      def: 'gpu:0'
      choices: ['gpu:0', 'gpu:1']
      lock: true
    oversubscribe:
      lock: true
    profile:
      def: 'PYT'
      choices: ['PYT', 'IA_CPU', 'IA_GPU']
    account:
      lock: true
    reservation:
      lock: true
    partition:
      def: 'cpubase_bycore_b1'
      lock: true
  SlurmFormSpawner:
    disable_form: false
    start_timeout: 900
    http_timeout: 900
    ui_args:
      lab:
        modules: ['jupyterlab-apps']
    profile_args:
      IA_CPU:
        name: 'Séquence IA - CPU'
        params:
          nprocs: 2
          runtime: 4
          memory: '2048'
          ui: 'lab'
          gpus: 'gpu:0'
          feature: ['cpu']
      IA_GPU:
        name: 'Séquence IA - GPU'
        params:
          nprocs: 2
          runtime: 4
          memory: '2048'
          oversubscribe: false
          ui: 'lab'
          gpus: 'gpu:1'
          feature: ['gpu']
      PYT:
        name: 'Séquence intro python'
        params:
          nprocs: 1
          runtime: 4
          memory: '1024'
          oversubscribe: false
          ui: 'lab'
          gpus: 'gpu:0'
          feature: ['cpu']

profile::freeipa::mokey::enable_user_signup: true
profile::freeipa::mokey::require_verify_admin: false

profile::accounts::skel_archives:
  - filename: cip101.zip
    source: https://github.com/calculquebec/cip101/archive/refs/heads/main.zip
  - filename: shell-lesson-data.zip
    source: https://swcarpentry.github.io/shell-novice/data/shell-lesson-data.zip
  - filename: dat201.zip
    source: https://github.com/calculquebec/dat201/archive/refs/heads/main.zip
  - filename: intro-machine-learning.zip
    source: https://github.com/calculquebec/intro-machine-learning/archive/refs/heads/master.zip
  - filename: pyt101.zip
    source: https://github.com/calculquebec/pyt101/archive/refs/heads/main.zip
  - filename: pyt102.zip
    source: https://github.com/calculquebec/pyt102/archive/refs/heads/main.zip
  - filename: dat203.zip
    source: https://github.com/calculquebec/dat203/archive/refs/heads/main.zip
  - filename: ia101.zip
    source: https://github.com/calculquebec/ia102/archive/refs/heads/master.zip
  - filename: ia103.zip
    source: https://github.com/calculquebec/ia103/archive/refs/heads/master.zip
  - filename: intro-apprentissage-IA.zip
    source: https://github.com/calculquebec/intro-apprentissage-IA/archive/refs/heads/main.zip


cron::job:
  spawn_cpu_nodes:
    command: "/opt/software/slurm/bin/scontrol update node=cpupool[1-15] state=power_up"
    minute: '0'
    hour: '8'
    date: '2,3,4,5'
    month: '6'
    weekday: '*'
    user: 'root'
    description: 'spawn cpu nodes'
    environment: ['CRON_TZ=America/New_York']
  spawn_all_nodes:
    command: "/opt/software/slurm/bin/scontrol update node=ALL state=power_up"
    minute: '0'
    hour: '8'
    date: '2,3,4,5'
    month: '6'
    weekday: '*'
    user: 'root'
    description: 'spawn all nodes'
    environment: ['CRON_TZ=America/New_York']
