jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    account:
      def: 'def-sponsor00'
    runtime:
      min: 3.5
      def: 4.0
      max: 8.0
    nprocs:
      min: 1
      def: 1
      max: 8
    memory:
      min: 1024
      max: 8092
      def: 4048
    gpus:
      def: 'gpu:0'
      choices: ['gpu:0', 'gpu:1']
    oversubscribe:
      def: true
      lock: false
    ui:
      def: 'lab'  # ['notebook', 'lab', 'terminal']
  SlurmFormSpawner:
    disable_form: false
    start_timeout: 900

profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'gcc', 'cuda/12.2', 'mpi4py/4.0.3']
jupyterhub::kernel::venv::packages:
  - numpy>2
  - pandas==2.2.3
  - matplotlib==3.10.0
  - plotnine==0.14.1
  - altair==5.4.1
  - vega_datasets
  - vl_convert_python
  - dask[array,distributed,diagnostics]==2025.2.0
  - graphviz
  - sparse
  - scipy==1.15.1
  - numba==0.61.2
  - torch==2.6.0
  - scikit-learn
  - pillow
  - pycuda==2025.1

profile::freeipa::mokey::enable_user_signup: true
profile::freeipa::mokey::require_verify_admin: false

profile::accounts::skel_archives:
  - filename: cache.zip
    source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip
  - filename: jupyter.zip
    source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1.0.1/jupyter-v1.0.1.zip
  - filename: main.zip
    source: https://github.com/calculquebec/cip101-exercices/archive/refs/heads/main.zip
  - filename: shell-lesson-data.zip
    source: https://swcarpentry.github.io/shell-novice/data/shell-lesson-data.zip

formation_extra::stripped_skel_archives:
  - filename: cip101_skel_extra.tar.gz
    source: https://github.com/calculquebec/formation_skels/archive/refs/heads/cip101.tar.gz

cron::job:
  spawn_cpu_nodes:
    command: "/opt/software/slurm/bin/scontrol update node=nodecpupool[1-15] state=power_up"
    minute: '0'
    hour: '8'
    date: '20,21'
    month: '5'
    weekday: '*'
    user: 'root'
    description: 'spawn cpu nodes'
    environment: ['CRON_TZ=America/New_York']
  spawn_all_nodes:
    command: "/opt/software/slurm/bin/scontrol update node=ALL state=power_up"
    minute: '0'
    hour: '8'
    date: '22,23'
    month: '5'
    weekday: '*'
    user: 'root'
    description: 'spawn all nodes'
    environment: ['CRON_TZ=America/New_York']
