jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 1024
            def: 1024
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'terminal'
    SlurmFormSpawner:
        disable_form: true
