jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 2048
            def: 2048
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true



profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'julia/1.8.5', 'ijulia-kernel/1.8']


# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']

