jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 2048
            def: 2048
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::enable_otp_auth: false

jupyterhub::admin_groups: ['helper']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'julia/1.8.5', 'ijulia-kernel/1.8']

profile::slurm::base::slurm_version: '23.02'

# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']

prometheus::global_config:
  scrape_interval: '1m'
  scrape_timeout: '1m'
  external_labels:
    cluster: "%{alias('cluster_name')}"
    cloud: "%{alias('cloud_name')}"
    team: 'calculquebec'
    purpose: 'formation'
    replica: '1'

prometheus::remote_write_configs:
  - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
    basic_auth:
      username: 'cqformation'
      password: "%{alias('prometheus_password')}"

