jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib']  # Pour démos en bonus

profile::accounts::skel_archives:
    - filename: pytshs102-main.zip
      source: https://github.com/calculquebec/pyt-shs102/archive/refs/heads/main.zip
