jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 2
            max: 2
        memory:
            min: 1024
            max: 3000
            def: 3000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::enable_otp_auth: false

jupyterhub::admin_groups: ['helper']

lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
jupyterhub::kernel::venv::packages: ['numpy', 'matplotlib']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'ir-kernel/4.2', 'ijulia-kernel/1.8']

profile::slurm::base::slurm_version: '23.02'

# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']


profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/lab101-exercices/archive/refs/heads/main.zip

    - filename: jupyter.zip
      source: https://drive.google.com/uc?export=download&id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB

    - filename: matplotlib.zip
      source: https://drive.google.com/uc?export=download&id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH


prometheus::global_config:
  scrape_interval: '1m'
  scrape_timeout: '1m'
  external_labels:
    cluster: "%{alias('cluster_name')}"
    cloud: "%{alias('cloud_name')}"
    team: 'calculquebec'
    purpose: 'formation'
    replica: '1'

prometheus::remote_write_configs:
  - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
    basic_auth:
      username: 'cqformation'
      password: "%{alias('prometheus_password')}"
