jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        nprocs:
            def: 4
            max: 4
        memory:
            max: 14000
            def: 14000
        ui:
            def: 'terminal'

profile::accounts::skel_archives:
    - filename: main-nbody.zip
      source: https://github.com/calculquebec/cq-formation-nbody/archive/refs/heads/main.zip
    - filename: main-convolution.zip
      source: https://github.com/calculquebec/cq-formation-convolution/archive/refs/heads/main.zip
