jupyterhub::enable_otp_auth: false

profile::slurm::base::slurm_version: '23.02'
prometheus::global_config:
  scrape_interval: '1m'
  scrape_timeout: '1m'
  external_labels:
    cluster: "%{alias('cluster_name')}"
    cloud: "%{alias('cloud_name')}"
    team: 'calculquebec'
    purpose: "%{alias('cluster_purpose')}"
    replica: '1'

prometheus::remote_write_configs:
  - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
    basic_auth:
      username: 'cqformation'
      password: "%{alias('prometheus_password')}"

