jupyterhub::enable_otp_auth: false
jupyterhub::admin_groups: ['helper']

prometheus::global_config:
  scrape_interval: '1m'
  scrape_timeout: '1m'
  external_labels:
    cluster: "%{alias('cluster_name')}"
    cloud: "%{alias('cloud_name')}"
    team: 'calculquebec'
    purpose: 'formation'
    replica: '1'

prometheus::remote_write_configs:
  - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
    basic_auth:
      username: 'cqformation'
      password: "%{alias('prometheus_password')}"
      
profile::slurm::base::slurm_version: '23.02'
profile::slurm::base::suspend_time: 7200
profile::slurm::base::resume_timeout: 7200

# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']


