jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        memory:
            max: 7400
            def: 7400

profile::cvmfs::client::repositories: ['cvmfs-config.computecanada.ca', 'soft.computecanada.ca', 'restricted.computecanada.ca']

profile::accounts::skel_archives:
    - filename: main-nbody.zip
      source: https://github.com/calculquebec/cq-formation-nbody/archive/refs/heads/main.zip
    - filename: main-convolution.zip
      source: https://github.com/calculquebec/cq-formation-convolution/archive/refs/heads/main.zip
