jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        memory:
            max: 3072
            def: 3072
        ui:
            def: 'lab'

jupyterhub::kernel::venv::packages: ['scikit-learn', 'matplotlib', 'pandas', 'pillow', 'numpy', 'torch', 'torchvision']

profile::accounts::skel_archives:
    - filename: ia103-main.zip
      source: https://github.com/calculquebec/ia103/archive/refs/heads/master.zip
