jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    nprocs:
      def: 2
      max: 2
    memory:
      max: 3000
      def: 3000

# Pour les prochaines fois, importer le matériel (valider avant): https://github.com/calculquebec/cq-openrefine
