jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 1024
            def: 1024
        oversubscribe:
            def: true
            lock: true
        partition:
            def: 'node'
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true


jupyterhub::admin_groups: ['helper']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'gcc/9', 'openmpi/4.0.3', 'boost-mpi/1.72.0']


# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']

profile::accounts::skel_archives:
    - filename: main-nbody.zip
      source: https://github.com/calculquebec/cq-formation-nbody/archive/refs/heads/main.zip
    - filename: main-convolution.zip
      source: https://github.com/calculquebec/cq-formation-convolution/archive/refs/heads/main.zip
