jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 1024
            def: 1024
        oversubscribe:
            def: true
            lock: true
        partition:
            def: 'node'
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::kernel::venv::packages: ['numpy', 'cupy']

profile::slurm::base::suspend_time: 7200
profile::slurm::base::resume_timeout: 7200

profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/cip201-serveurs-calcul/archive/refs/heads/main.zip
    - filename: will-cite.zip
      source: https://drive.google.com/uc?export=download&id=11vO_wCCvUUGxg6JmpvQjck6Q6WU-LL9t
