jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 4098
            def: 4098
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true




profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'julia', 'ijulia-kernel/1.8']

jupyterhub::kernel::venv::packages: []


profile::accounts::skel_archives:
    - filename: main.zip
      source: https://github.com/calculquebec/cq-formation-intro-snowflake/archive/refs/heads/main.zip

    - filename: jupyter.zip
      source: https://drive.google.com/uc?export=download&id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB
