jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 4
            max: 4
        memory:
            min: 1024
            max: 22000
            def: 21000
        gpus:
            def: 'gpu:1'
            choices: ['gpu:1']
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true



lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
jupyterhub::kernel::venv::packages: ['cupy']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']


# For TF cloud, password is pre-set from variable
profile::users::ldap::users:
    user:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']

    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']

profile::accounts::skel_archives:
    - filename: jupyter.zip
      source: https://drive.google.com/uc?id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB&export=download
