jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 4
            max: 4
        memory:
            min: 1024
            max: 30000
            def: 29000
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'paraview'
    SlurmFormSpawner:
        disable_form: true




profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'gcc/9.3.0', 'openmpi/4.0.3', 'paraview-offscreen/5.9.1']
