jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        nprocs:
            def: 2
            max: 2
        memory:
            max: 18000
            def: 18000
        gpus:
            def: 'gpu:1'
            choices: ['gpu:1']

jupyterhub::kernel::venv::packages: ['cupy']
