jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        account:
            def: 'def-sponsor00'
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 4
            max: 4
        memory:
            min: 1024
            max: 22000
            def: 21000
        gpus:
            def: 'gpu:1'
            choices: ['gpu:1']
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::kernel::venv::packages: ['cupy']

profile::accounts::skel_archives:
    - filename: jupyter.zip
      source: https://drive.google.com/uc?id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB&export=download
